name: Daily Rollup

on:
  schedule:
    - cron: "30 6 * * *"  # Runs every day at 12:20am CST, 1:30am EST (6 AM UTC) to avoid concurrent running with main.yml
  workflow_dispatch:     # lets you trigger manually

permissions:
  contents: write

jobs:
  rollup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: Install dependencies
        run: pip install pandas pytz

      - name: Run daily rollup
        run: python IDOC_Lockdown_Daily_Aggregation.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/daily_scrape.csv data/master_tracker.csv
          git commit -m "Daily rollup update [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
