name: Daily Aggregate

on:
  schedule:
    - cron: "0 5 * * *"   # 12:00 AM CST every day
  workflow_dispatch:     # optional manual trigger

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Download hourly CSVs
        uses: actions/download-artifact@v4
        with:
          name: lockdown-data
          path: ./hourly_files

      - name: Run daily aggregation
        run: python daily_aggregate.py

      - name: Upload updated master CSV
        uses: actions/upload-artifact@v4
        with:
          name: master-lockdown
          path: master_lockdown.csv
