name: Run Scraper Hourly

on:
  schedule:
    - cron: "46 * * * *"   # every hour, on the hour (UTC)
  workflow_dispatch:       # lets you trigger manually too

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run scraper
        run: python IDOC_Lockdown_Web_Scraping.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: lockdown-data
          path: "*.csv"
      - name: Upload master CSV
        uses: actions/upload-artifact@v4
        with:
          name: master-lockdown
          path: master_lockdown.csv
      - name: Download master lockdown CSV
        uses: actions/download-artifact@v4
        with:
          name: master-lockdown
          path: ./data
